import CustomerPaymentAPI from "/API/customer/customerPaymentAPI.js";

const payment_API = new CustomerPaymentAPI();

$("#payment-Popup-submit-ID").on('click', async (event) => {
    event.preventDefault();

    const customerPaymentModel = {
        // payment_id: $("#payment_id").val(), // not needed if generated by backend
        amount: $("#payment-amount").val(),
        loan_id: $("#payment-loan-id").val(),
        payment_type: $("#payment-type").val(),
        date: $("#payment-date").val()
    };

    console.log("customerPaymentModel:", customerPaymentModel);

    try {
        await payment_API.savePayment(customerPaymentModel);
        await Swal.fire({
            icon: 'success',
            title: 'Payment is successful',
            text: 'Your payment has been processed successfully'
        });
        window.location.reload();
    } catch (error) {
        console.log("failed", error);
    }
});
